# Generated by Django 2.1.7 on 2019-03-05 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='experience',
            new_name='drive_exp',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='location',
            new_name='eircode',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='name',
            new_name='f_name',
        ),
    ]
