# Generated by Django 2.1.7 on 2019-03-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190305_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='age',
            new_name='licence_type',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='eircode',
        ),
        migrations.AddField(
            model_name='driver',
            name='DOB',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='driver',
            name='NCB',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='driver',
            name='address',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='driver',
            name='emp_status',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='driver',
            name='l_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='driver',
            name='f_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
