# Generated by Django 2.1.7 on 2019-03-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190311_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='licence_type',
            new_name='address1',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='DOB',
            new_name='dob',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='NCB',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='address',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='drive_exp',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='emp_status',
        ),
        migrations.AddField(
            model_name='driver',
            name='address2',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
