# Generated by Django 2.1.7 on 2019-03-15 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20190315_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('Driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.Driver')),
                ('car_type', models.CharField(blank=True, max_length=20)),
                ('car_reg', models.CharField(blank=True, max_length=20)),
                ('car_milage', models.CharField(blank=True, max_length=20)),
                ('engine_size', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
