# Generated by Django 2.1.7 on 2019-03-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20190320_1506'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistrationData',
        ),
        migrations.AddField(
            model_name='journeys',
            name='start_location',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
