# Generated by Django 2.1.7 on 2019-03-22 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20190321_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fatigue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fatigue_level', models.PositiveIntegerField(blank=True)),
                ('Driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Driver')),
            ],
        ),
        migrations.CreateModel(
            name='Smoothness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Smoothness_level', models.PositiveIntegerField(blank=True)),
                ('Driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Driver')),
            ],
        ),
        migrations.CreateModel(
            name='Speed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed_level', models.PositiveIntegerField(blank=True)),
                ('Driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Driver')),
            ],
        ),
        migrations.CreateModel(
            name='TimeOfDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_day_level', models.PositiveIntegerField(blank=True)),
                ('Driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Driver')),
            ],
        ),
    ]
