# Generated by Django 2.1.7 on 2019-03-22 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_fatigue_smoothness_speed_timeofday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speed',
            name='id',
        ),
        migrations.AddField(
            model_name='speed',
            name='Journeys',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.Journeys'),
            preserve_default=False,
        ),
    ]
