# Generated by Django 2.1.7 on 2019-04-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_fatigue_smoothness_speed_timeofday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeys',
            name='start_time',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
