# Generated by Django 2.1.7 on 2019-04-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20190409_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeys',
            name='end_time',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
