# Generated by Django 2.1.7 on 2019-03-22 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20190322_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fatigue',
            name='Driver',
        ),
        migrations.RemoveField(
            model_name='fatigue',
            name='id',
        ),
        migrations.RemoveField(
            model_name='smoothness',
            name='Driver',
        ),
        migrations.RemoveField(
            model_name='smoothness',
            name='id',
        ),
        migrations.RemoveField(
            model_name='timeofday',
            name='Driver',
        ),
        migrations.RemoveField(
            model_name='timeofday',
            name='id',
        ),
        migrations.AddField(
            model_name='fatigue',
            name='Journeys',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.Journeys'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smoothness',
            name='Journeys',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.Journeys'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeofday',
            name='Journeys',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.Journeys'),
            preserve_default=False,
        ),
    ]
