# Generated by Django 2.1.7 on 2019-04-11 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20190409_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month_journey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(blank=True, max_length=20)),
                ('monthly_journey_score', models.PositiveIntegerField(blank=True)),
                ('Driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Driver')),
            ],
        ),
    ]
