# Generated by Django 2.1.7 on 2019-03-22 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20190322_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speed',
            name='Driver',
        ),
    ]
