# Generated by Django 2.1.7 on 2019-04-14 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_real_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day_journey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(blank=True, max_length=20)),
                ('daily_journey_score', models.PositiveIntegerField(blank=True)),
                ('Driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Driver')),
            ],
        ),
        migrations.CreateModel(
            name='Week_journey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(blank=True, max_length=20)),
                ('weekly_journey_score', models.PositiveIntegerField(blank=True)),
                ('Driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Driver')),
            ],
        ),
    ]
