# Generated by Django 2.1.7 on 2019-04-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_day_journey_week_journey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=20)),
                ('lname', models.CharField(blank=True, max_length=20)),
                ('age', models.CharField(blank=True, max_length=20)),
                ('save_address', models.CharField(blank=True, max_length=20)),
                ('monthlyFinalInsurancePrice', models.CharField(blank=True, max_length=20)),
                ('area', models.CharField(blank=True, max_length=20)),
                ('car_model', models.CharField(blank=True, max_length=20)),
                ('total_cost', models.CharField(blank=True, max_length=20)),
                ('excess', models.CharField(blank=True, max_length=20)),
                ('licenceType', models.CharField(blank=True, max_length=20)),
                ('ncbYears', models.CharField(blank=True, max_length=20)),
                ('namedExp', models.CharField(blank=True, max_length=20)),
                ('penPoints', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
